### ISSUE TITLE
Add frameworktest?

### ISSUE THREAD

**Issue by chillu** [silverstripe/cwp-recipe-kitchen-sink#12]
I noticed https://github.com/silverstripe/cwp-recipe-kitchen-sink doesn’t include https://github.com/silverstripe/silverstripe-frameworktest. Which is fine in terms of release testing since it’s not a supported module. But it also means you’ll likely miss certain variations in your testing, for example having a ModelAdmin with enough records to show pagination, or having readonly and disabled versions of all form fields. I’m trying to get OSSers using the kitchen sink as their baseline as well, and they’re already using frameworktest. Any reason we can’t add it?

**Comment by robbieaverill** [comment]
Good idea! If we add it as a dev requirement then it shouldn’t be included in recipe release plans. Having it would be very useful for testing recipes, for sure
