### ISSUE TITLE
2.2/2.x: Test failures

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp-recipe-kitchen-sink#13]
We have two test failures at the moment:

- [x] SilverStripe\Admin\Tests\LeftAndMainTest::testLeftAndMainSubclasses
- [x] SilverStripe\SecurityReport\Tests\SubsitesReportTest::testGetMemberGroups

The first one should be fixable. The test in question wasn't even running in 2.1 until [it was re-enabled](https://github.com/silverstripe/silverstripe-admin/pull/384).

The second one is a functional regression logged as https://github.com/silverstripe/silverstripe-securityreport/issues/38

**Comment by robbieaverill** [comment]
Subsites has been reverted.

https://github.com/silverstripe/silverstripe-admin/commit/249e33a56d53b68392b6dc2d3b4d93179dec3387 caused the LeftAndMain test to fail. It previously wasn't actually asserting anything. I'll rewrite it.

**Comment by robbieaverill** [comment]
PR for LeftAndMain https://github.com/silverstripe/silverstripe-admin/pull/704/files

**Comment by dhensby** [comment]
Are we done here?

**Comment by robbieaverill** [comment]
Yep, we have another issue to fix the rest
