### ISSUE TITLE
MASTER/2.3: Unit test failures

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp-recipe-kitchen-sink#18]
At time of writing (updated), these are the failing unit tests in the master branch (CWP 2.3.x-dev):

https://travis-ci.org/silverstripe/cwp-recipe-kitchen-sink/jobs/468593237

## default testsuite

- [x] SilverStripe\Forms\Tests\TreeMultiselectFieldTest::testEmpty
Failed asserting that '<div class="TreeDropdownField treemultiselect multiple searchable searchable "
- [x] TractorCow\Fluent\Tests\Extension\FluentSiteTreeExtensionTest::testUpdateCMSFields (https://github.com/tractorcow-farm/silverstripe-fluent/commit/d5a278e685b244f88efea632c0f2ab66e22c4c8e)

## recipe-collaboration

- [x] PHP Fatal error:  Uncaught Error: Call to a member function setOwner() on null in /home/travis/build/silverstripe/cwp-recipe-kitchen-sink/vendor/silverstripe/framework/src/Core/Extensible.php:139 (https://github.com/silverstripe/silverstripe-framework/pull/8505)

There are no functional changes between the 2.2 branch and master at the moment, only the following modules added to composer.json:

```
+        "silverstripe/frameworktest": "dev-master",
+        "silverstripe/graphql-devtools": "1.x-dev",
+        "silverstripe/recipe-testing": "1.x-dev"
```

I suspect that frameworktest might be causing some of this.

## recipe-content-blocks

- [x] [silverstripe-elemental#585](https://github.com/dnadesign/silverstripe-elemental/pull/585)

**Comment by robbieaverill** [comment]
Regarding the setOwner() on null, I think it's related to the fact that advancedworkflow has a `public $workflowService` prop that is used for dependency injection. I've added public getter/setters in https://github.com/symbiote/silverstripe-queuedjobs/pull/222, but the bug won't be fixed there until we can reduce the visibility of that prop to protected (major semver change). The framework PR also fixes the error, and can be merged safely into a patch release.

**Comment by brynwhyman** [comment]
Updated to remove reference to the subsite test failure (which doesn't appear to be happening on master)

**Comment by robbieaverill** [comment]
Oh yeah, we reverted the change in framework that was causing those test failures =D

**Comment by Cheddam** [comment]
I've raised an issue on the frameworktest module, as it's the custom GraphQL schema in this module that's causing the premature query issue: https://github.com/silverstripe/silverstripe-frameworktest/issues/59

Currently awaiting feedback from people with more knowledge on this front; this story is blocked until then.

**Comment by robbieaverill** [comment]
@Cheddam I'd suggest having a go at adding some "database is ready" checks to the GraphQL middleware and see if that fixes the issue. If there's any other feedback you need to unblock this issue please let me know and I'll have a closer look!

**Comment by brynwhyman** [comment]
Check out #24 when you're looking at this, there may be some related failures to backport to 2.2

**Comment by robbieaverill** [comment]
Once https://github.com/silverstripe/silverstripe-graphql/pull/208 is merged on green I'll re-run the remaining kitchen sink build that failed, then it's all green and we can close this

**Comment by robbieaverill** [comment]
Yay, all green: https://travis-ci.org/silverstripe/cwp-recipe-kitchen-sink/builds/485353029
