### ISSUE TITLE
2.2: Unit test failures

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/cwp-recipe-kitchen-sink#20]
Failures as of 24/01/2019:

### framework-core

- [x] [`1) SilverStripe\Forms\Tests\TreeMultiselectFieldTest::testEmpty`](https://github.com/silverstripe/silverstripe-framework/pull/8755)

### recipe-content-blocks

- [x] [`1) DNADesign\Elemental\Tests\Extensions\ElementalAreasExtensionTest::testGetElementalTypesSortsAlphabetically
`](https://github.com/dnadesign/silverstripe-elemental/pull/579)
- [x] [`2) DNADesign\Elemental\Tests\Extensions\ElementalAreasExtensionTest::testGetElementalTypesAreNotSortedAlphabetically`](https://github.com/dnadesign/silverstripe-elemental/pull/579)

### Default

- [ ] `1) SilverStripe\Subsites\Tests\SubsiteTest::testDomainProtocol with data set #3 ('SilverStripe\Subsites\Model\Subsite', 'domaintest4', false, 'https://www.primary.com/')`
- [ ] `2) SilverStripe\Subsites\Tests\SubsiteTest::testDomainProtocol with data set #11 ('SilverStripe\Subsites\Model\Subsite', 'domaintest4', true, 'https://www.primary.com/')`

**Comment by robbieaverill** [comment]
For some of the framework-core testsuite: https://github.com/silverstripe/silverstripe-framework/pull/8654

**Comment by robbieaverill** [comment]
https://travis-ci.org/silverstripe/cwp-recipe-kitchen-sink/builds/457825210 is green!

**Comment by robbieaverill** [comment]
Reopened, two subsites test failures. I've looked at these before and they don't fail when run in isolation, so must be a global state issue. Will have a hunt for the culprit.

**Comment by robbieaverill** [comment]
I disabled transactions in the dodgy subsite test, all green again
