### ISSUE TITLE
Fix failing password validation tests

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/cwp-recipe-kitchen-sink#21]
There are a number of test failures in CWP 2.2 now, appearing mostly relating to the recent password validation change.

This will be marked as 'expected test failures' in the 2.2 release but they should be resolved.

**Comment by robbieaverill** [comment]
Oh also, most of this is just waiting to be reviewed: https://github.com/silverstripe/silverstripe-framework/pull/8654

**Comment by brynwhyman** [comment]
Closed for #20
