### ISSUE TITLE
2.1 test failures

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/cwp-recipe-kitchen-sink#24]
Some failures have popped up on the 2.1 branch. https://travis-ci.org/silverstripe/cwp-recipe-kitchen-sink/builds/457824714

 As at 26/01/19 failures are:
- [x] `SilverStripe\Forms\Tests\TreeMultiselectFieldTest::testEmpty`

- [x] `SilverStripe\ORM\Connect\DatabaseException: Couldn't run query` (causing 34 errors) --probably related to the issues being resolved #18

**Comment by robbieaverill** [comment]
💚 https://travis-ci.org/silverstripe/cwp-recipe-kitchen-sink/builds/484733929
