### ISSUE TITLE
Fix 2.2 failing builds

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/cwp-recipe-kitchen-sink#27]
Failed on 27/02/19

https://travis-ci.org/silverstripe/cwp-recipe-kitchen-sink/builds/498724570

```There was 1 failure:
1) SilverStripe\CronTask\Tests\CronTaskControllerTest::testDefaultQuietFlagOutput
Failed asserting that '2019-47-26 13:: - CWP\PDFExport\Tasks\CleanupGeneratedPdfDailyTask will run at 2019-02-27 00:00:00.
2019-47-26 13:: - SilverStripe\CronTask\Tests\CronTaskTest\TestCron will run at 2019-02-26 14:00:00.
' matches PCRE pattern "#2019-46-26#".
/home/travis/build/silverstripe/cwp-recipe-kitchen-sink/vendor/phpunit/phpunit/phpunit:52

**Comment by robbieaverill** [comment]
Looks like a legit bug, maybe we are doing bad date formatting

**Comment by robbieaverill** [comment]
Yeah this our date format in a unit test: `DBDatetime::now()->Format('Y-m-d')` - that's wrong, will update shortly

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-crontask/pull/51

**Comment by robbieaverill** [comment]
Merged and restarted the builds - I'll reopen if that didn't fix it
