### ISSUE TITLE
Fix queuedjob-security extension tests

### ISSUE THREAD

**Issue by dnsl48** [silverstripe/cwp-recipe-kitchen-sink#48]
A TravisCI test is [failing](https://travis-ci.org/silverstripe/cwp-recipe-kitchen-sink/jobs/613222391) because some of queuedjobs tests create HTTPRequest without initializing Injector with it.
Later, security-extensions try to access the request through injector and fail.
Need to come up with a solution for that (since that's integration issue and not an issue of each one of those on their own).

## PRs

 - [x] https://github.com/silverstripe/cwp-recipe-kitchen-sink/issues/48

**Comment by emteknetnz** [comment]
This is now passing https://travis-ci.org/silverstripe/cwp-recipe-kitchen-sink/branches - we can close this PR?

**Comment by dnsl48** [comment]
yes, the PR link is incorrect, but I remember reviewing the patch myself :) closing
