### ISSUE TITLE
Broken travis build for 2.2

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/cwp-recipe-kitchen-sink#50]
https://travis-ci.org/silverstripe/cwp-recipe-kitchen-sink/builds/625881936

The first failure is silverstripe/assets FileTest.php testCanViewInheritsRecursively()

Unit tests pass for assets module if run on the assets module itself

Seems to be a complication when running with the versioned module, specifically canViewVersioned() which is called by canView() within the failing unit test

Have tried upgrading both silverstripe/assets and silverstripe/versioned to the 1.4.x-dev and 1.5.x-dev respectively to match kitchen-sink 2.3, however the test still fails.  The same test passes in 2.3

**Comment by emteknetnz** [comment]
PR: https://github.com/silverstripe/cwp-core/pull/82

**Comment by emteknetnz** [comment]
^ Above PR is green and ready for merge

**Comment by emteknetnz** [comment]
PR for 2.3 to get memory to 3G and ensure that future merge ups work correct
https://github.com/silverstripe/cwp-recipe-kitchen-sink/pull/53

**Comment by maxime-rainville** [comment]
All PRs have been merged. The PR build was green, so the branch build should be green as well ... if it isn't, it's probably going to be a different problem any way.
