### ISSUE TITLE
Use utf8mb4 by default

### ISSUE THREAD

**Issue by chillu** [silverstripe/cwp-recipe-kitchen-sink#80]
We've recommended this since 4.6.0 I think? Anyway, it has the potential to cause side effects (indexes too long), so we should test with that baseline.

**Comment by brynwhyman** [comment]
Isn't this included for all new projects by default already, I thought that would have applied to a kitchen-sink install too? 

https://docs.silverstripe.org/en/4/changelogs/4.7.0/#default-mysql-collation-updated

https://github.com/silverstripe/recipe-core/commit/9b1350ea53bb184b6b816211851824a414bdbe5b

**Comment by chillu** [comment]
Right, so the problem is that the `app/_config/mysite.yml` file gets added during `composer install`, but never got committed to the repo itself. It exists in local state only, which happens to work in the way we deploy projects. Its a bit confusing, but you're right - it should've applied already, just behind the scenes!
